import Head from 'next/head'

import { Flex } from '@chakra-ui/layout'

import { Chat } from '../components/Chat'
import { Sidebar } from '../components/Sidebar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        bg="#a7bcff"
        height="100vh"
        alignItems="center"
        justifyContent="center"
        p="0.5rem"
      >
        <Flex overflow="hidden" borderRadius="10px" w="100%" h="100%">
          <Sidebar />
          <Chat />
        </Flex>
      </Flex>
    </>
  )
}
