import Head from 'next/head'

import { Flex } from '@chakra-ui/layout'
import { useBreakpointValue } from '@chakra-ui/media-query'

import { Chat } from '../components/Chat'
import { Sidebar } from '../components/Sidebar'
import { useChat } from '../hooks/useChat'

export default function Home() {
  const { data } = useChat()

  const isMobileVersion = useBreakpointValue({
    base: true,
    md: false,
    lg: false,
    xl: false
  })
  return (
    <>
      <Head>
        <title>Home | Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        bg="#a7bcff"
        height="100vh"
        alignItems="center"
        justifyContent="center"
        p={{ base: '0', xl: '0.5rem' }}
      >
        {isMobileVersion ? (
          <Flex
            overflow="hidden"
            borderRadius={{ base: '0', xl: '10px' }}
            w="100%"
            h="100%"
          >
            {!data.chatId ? <Sidebar /> : <Chat />}
          </Flex>
        ) : (
          <Flex
            overflow="hidden"
            borderRadius={{ base: '0', xl: '10px' }}
            w="100%"
            h="100%"
          >
            <Sidebar />
            <Chat />
          </Flex>
        )}
      </Flex>
    </>
  )
}
